-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 10:57:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_auredubot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_auredubot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_auredubot` DEFAULT CHARACTER SET utf8 ;
USE `db_auredubot` ;

-- -----------------------------------------------------
-- Table `db_auredubot`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `title` VARCHAR(60) NOT NULL,
  `slug` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`locales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`locales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identifie` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `localeID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_countries_locales1_idx` (`localeID` ASC),
  CONSTRAINT `fk_countries_locales1`
    FOREIGN KEY (`localeID`)
    REFERENCES `db_auredubot`.`locales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `firstName` VARCHAR(60) NOT NULL,
  `lastName` VARCHAR(80) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(60) NOT NULL,
  `street` VARCHAR(255) NULL,
  `streetNumber` VARCHAR(255) NULL,
  `ciity` VARCHAR(60) NOT NULL,
  `postalCode` VARCHAR(10) NOT NULL,
  `seen` BOOLEAN NULL DEFAULT 0,
  `valid` BOOLEAN NULL DEFAULT 0,
  `confirmed` BOOLEAN NULL DEFAULT 0,
  `confirmation_code` VARCHAR(45) NULL,
  `roleID` INT NOT NULL,
  `countryID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`roleID` ASC),
  INDEX `fk_users_countries1_idx` (`countryID` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roleID`)
    REFERENCES `db_auredubot`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_countries1`
    FOREIGN KEY (`countryID`)
    REFERENCES `db_auredubot`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;locales


-- -----------------------------------------------------
-- Table `db_auredubot`.`registrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`registrations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `nbAdults` SMALLINT NOT NULL,
  `nbChildren` SMALLINT NULL,
  `baby` BOOLEAN NULL DEFAULT 0,
  `clearing` BOOLEAN NULL DEFAULT 1,
  `totalPrice` FLOAT NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registrations_users1_idx` (`userID` ASC),
  CONSTRAINT `fk_registrations_users1`
    FOREIGN KEY (`userID`)
    REFERENCES `db_auredubot`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestanps` TIMESTAMP NULL,
  `title` VARCHAR(60) NOT NULL,
  `contant` TEXT NOT NULL,
  `rating` SMALLINT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`userID` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`userID`)
    REFERENCES `db_auredubot`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`activityTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`activityTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `name` VARCHAR(255) NOT NULL,
  `localeID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activityTypes_locales1_idx` (`localeID` ASC),
  CONSTRAINT `fk_activityTypes_locales1`
    FOREIGN KEY (`localeID`)
    REFERENCES `db_auredubot`.`locales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `name` VARCHAR(255) NOT NULL COMMENT '				',
  `description` TEXT NULL,
  `photo` BINARY NULL,
  `distance` SMALLINT NULL,
  `website` VARCHAR(255) NULL,
  `activityTypeID` INT NOT NULL,
  `localeID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activities_locales1_idx` (`localeID` ASC),
  INDEX `fk_activities_activityTypes1_idx` (`activityTypeID` ASC),
  CONSTRAINT `fk_activities_locales1`
    FOREIGN KEY (`localeID`)
    REFERENCES `db_auredubot`.`locales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activities_activityTypes1`
    FOREIGN KEY (`activityTypeID`)
    REFERENCES `db_auredubot`.`activityTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`getawayPlaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`getawayPlaces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `name` VARCHAR(60) NOT NULL,
  `distance` SMALLINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`getaways`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`getaways` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `name` VARCHAR(60) NOT NULL,
  `description` TEXT NULL,
  `photo` BINARY NULL,
  `website` VARCHAR(255) NULL,
  `getawayPlaceID` INT NOT NULL,
  `localeID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_getaways_getawayPlaces1_idx` (`getawayPlaceID` ASC),
  INDEX `fk_getaways_locales1_idx` (`localeID` ASC),
  CONSTRAINT `fk_getaways_getawayPlaces1`
    FOREIGN KEY (`getawayPlaceID`)
    REFERENCES `db_auredubot`.`getawayPlaces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_getaways_locales1`
    FOREIGN KEY (`localeID`)
    REFERENCES `db_auredubot`.`locales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`zones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`zones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `name` VARCHAR(60) NOT NULL,
  `photo` BINARY NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_auredubot`.`commodities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_auredubot`.`commodities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamps` TIMESTAMP NULL,
  `name` VARCHAR(60) NOT NULL,
  `description` TEXT NULL,
  `icon` VARCHAR(45) NULL,
  `photo` BINARY NULL,
  `zoneID` INT NOT NULL,
  `localeID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commodities_zones1_idx` (`zoneID` ASC),
  INDEX `fk_commodities_locales1_idx` (`localeID` ASC),
  CONSTRAINT `fk_commodities_zones1`
    FOREIGN KEY (`zoneID`)
    REFERENCES `db_auredubot`.`zones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commodities_locales1`
    FOREIGN KEY (`localeID`)
    REFERENCES `db_auredubot`.`locales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
